version: "2"
services:
  collector:
    image: otel/opentelemetry-collector:latest
    expose:
      - 4317
    command: ["--config=/etc/collector-config.yaml"]
    volumes:
      - ./collector.yaml:/etc/collector-config.yaml
  
  go:
    build: ./go 
    ports:
      - 8080:8080
    environment: 
      - GIN_MODE=release
    depends_on: 
      - collector