version: "2"
services:
  collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317
    command: ["--config=/etc/collector-config.yaml"]
    volumes:
      - ./collector.yaml:/etc/collector-config.yaml
  
  go:
    build: ./go
    ports:
      - 8080:8080